name: flutter_firebase_kurs_login
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  user_details_repository:
    path: packages/user_details_repository
  bloc: ^8.1.0
  equatable: ^2.0.3
  firebase_core: ^2.27.1
  flow_builder: ^0.0.10
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  font_awesome_flutter: ^10.1.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.6.0
  freezed: ^2.5.2
  go_router: ^13.2.4
  google_fonts: ^6.2.1
  meta: ^1.11.0
  freezed_annotation: ^2.4.1
  

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/logo_ball.png
    - assets/logo_full.png